
title: "Template Quarto"
author: "Course"
project: 
    type: website
    output-dir: website
    render:
        - index.qmd
# preview: 
#     port: 2222
format: 
    html:
        page-layout: article
        theme: [darkly]