title: "Quarto Template"
author: "Data Science and Machine Learning Class"
project: 
    type: website
    output-dir: website
    preview: 
        port: 2222
    render:
        - index.qmd
        - about.qmd
website:
    navbar:
        left:
            - text: "Home"
              href: index.qmd
            - text: "Koen's Page"
              href: about.qmd
    favicon: img/favicon.png
format: 
    html:
        page-layout: article
        theme: [cosmo, style.scss]